apiVersion: v1
kind: Secret
metadata:
  name: filehub-secret
  namespace: filehub
type: Opaque
stringData:
  DATABASE_URL: "postgresql://filehub:filehub123@filehub-db:5432/filehub?schema=public"
  POSTGRES_PASSWORD: "filehub123"
